title: Olli Kuparinen
tagline: Languages, technology and cycling might appear here.
description: Olli Kuparinen's website to share professional and unprofessional information.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
